version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - ./static_volume:/movie_admin/staticfiles
    depends_on:
      - web
    restart: "on-failure"

  web:
    container_name: django_admin
    build: .
    environment:
      - SECRET_KEY=csdmklcmklLK#MKMFCLKMDLKvmklsmdlkvmvlmdslkvsmdvl
      - DBNAME=postgres
      - DBUSER=postgres
      - DBPASSWORD=postgres
      - DBHOST=postgres
      - DBPORT=5432
    volumes:
      - ./static_volume:/movie_admin/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    restart: always

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - C:\Users\djvor\PycharmProjects\Admin_panel_sprint_2\movies_admin\helm\postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  static_volume: