version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - ./static_volume:/movie_admin/staticfiles
    depends_on:
      - web
    restart: "on-failure"

  web:
    container_name: django_admin
    build: .
    volumes:
      - ./static_volume:/movie_admin/staticfiles
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  static_volume:
  postgres_data: