# Generated by Django 3.1.6 on 2021-02-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(blank=True, upload_to='media/files', verbose_name='Путь до файла'),
        ),
    ]
